### ISSUE TITLE
Problems with ajax fields / TreeDropdownField

### ISSUE THREAD

**Issue by wernerkrauss** [sheadawson/silverstripe-shortcodable#12]
Tried a TreeDropdown to make a searchable dropdown, unfortunately i get  an error:
`I can't handle sub-URLs of a Form object.`

url was: `http://localhost:8080/ShortcodableController/ShortcodeForm/field/id/tree?id_SubsiteID=NaN`

**Comment by sheadawson** [comment]
Cheers for reporting. Fixed in https://github.com/sheadawson/silverstripe-shortcodable/commit/40929c75e2a54fa3da9067e68b1a290b1ebad525
