### ISSUE TITLE
Possibility to disable automatic ID dropdown

### ISSUE THREAD

**Issue by wernerkrauss** [sheadawson/silverstripe-shortcodable#13]
I have a shortcode named like the DataObject that just uses the tile instead of the ID (yes, i know, that's bad, but for historic reasons).

There is no built in functionality to disable the automatic ID dropdown now.

**Comment by sheadawson** [comment]
Can you use the extension hook ShortcodableController->ShortcodeForm-> updateShortcodeForm ?

**Comment by wernerkrauss** [comment]
I did this already, but it feels a bit wrong, cause `updateShortcodeForm` is global, so i first have to check if it's the shortcode i want to modify.

Best would be that the shortcode itself could update the shortcode form, or disable / overwrite the id field. (BTW: i tried to use your quickAddNew button, had to overwrite the id field again, but it didn't work due to controller issues)

**Comment by sheadawson** [comment]
I think what you're trying to do here sounds a like a bit of an edge case. If you'd like to make a pull request for this though you are welcome to. Closing for now :)
