### ISSUE TITLE
JS error on SS3.2.0-rc1

### ISSUE THREAD

**Issue by micschk** [sheadawson/silverstripe-shortcodable#14]
"Uncaught ReferenceError: tinymce is not defined" from editor_plugin.js

[ ] button appears in the editor, but the module doesn't work

**Comment by mi32dogs** [comment]
I have the same problem in SS 3.2.0

**Comment by kinglozzer** [comment]
Possibly related to #17

**Comment by sheadawson** [comment]
Just tested in 3.2 after merging #17, seems to work fine now thanks lozzer :)
