### ISSUE TITLE
Viewable data doesn't have method singular_name

### ISSUE THREAD

**Issue by sheadawson** [sheadawson/silverstripe-shortcodable#21]
Referenced in ShortcodableController line 30

**Comment by sekjal** [comment]
Looks like this line is now 33, just for updated reference.

Got something similar when implementing Shortcodable on an extension to Member (it was on MemberExtension, not ViewableData).  My solution was to add a singular_name() method on my extension that returned the string I wanted.

I would think anything inheriting from DataObject would be all set with this; aside from Extensions, are there any other classes upon which Shortcodable might be applied that _aren't_ DataObjects?

**Comment by sheadawson** [comment]
Fixed and released as 2.0, see readme for details on upgrades. Cheers!

**Comment by sheadawson** [comment]
https://github.com/sheadawson/silverstripe-shortcodable/commit/c0b7dd77a037d885b382e00ed19cfb874545e65f
