### ISSUE TITLE
shortcodable.js - Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by camexapps** [sheadawson/silverstripe-shortcodable#36]
Appears to be from the getPlaceholderClasses function. Perhaps some checking method to see if the 'placeholderclasses' data attribute exists first, such as:

`if ($(this).data('placeholderclasses')) {
					return $(this).data('placeholderclasses').split(',');
				}`

**Comment by sheadawson** [comment]
Thanks for reporting!
