### ISSUE TITLE
Issues with copy and pasting in tinymce editor.

### ISSUE THREAD

**Issue by jamesbolitho** [sheadawson/silverstripe-shortcodable#38]
Hi Shea,

Firstly thank you for creating such a useful module.

When I have shortcodable installed on Silverstripe 3.3.2, I am losing the ability to paste text into the editor field. Either by using cmd v on mac or through "Paste from Word" in the editor.  Just thought I would flag this up if firstly to see if you can replicate this issue your end.  I have tried Firefox and Safari and the results are the same.

My quick work around was to simply comment out lines 33 through to 43 in the shortcodable/javascript/editor_plugin.js which has resolved the problem relating to the pasting of text.

Let me know if you require further information.  

Thanks,

James

**Comment by sheadawson** [comment]
Thanks for reporting!
