### ISSUE TITLE
Quotation marks in text fields

### ISSUE THREAD

**Issue by jacobaarnold** [sheadawson/silverstripe-shortcodable#43]
I notice if I add a TextField or TextareaField to my FieldList, any double quotation marks entered break the short code in preview and published views. Is there any fix for this? Thanks!

**Comment by janneklouman** [comment]
Has anyone managed to solve this?

**Comment by micschk** [comment]
Double quotes are part of the shortcode markup, so they're tricky/should not be used in attributes. 

A workaround would be to use typographic quotation marks (“ & ”) instead of straight "s.
