### ISSUE TITLE
Help configuring for inserting html blocks

### ISSUE THREAD

**Issue by MondID** [sheadawson/silverstripe-shortcodable#48]
Hi all -

I should still be considered a newbie to Silverstripe's coding [coming from a front-end design space] so I am reaching out for a little practical help here. 

I'd love to use this to insert html code(s) into my pages, such as provided by GetResponse for example - or any other forms we develop internally. I understand that this will require some reconfiguration/recoding - and that's where I'll be venturing out of my comfort zone. Could anyone help me with this please?

Happy to pay for time, if/when desired. Having this included on our site would be marvellous. 

Looking forward to hear from you....

**Comment by wernerkrauss** [comment]
Hi, if you need ad-hoc help come over to IRC (freenode, #silverstripe), there is also a slack channel where you can find someone, there is also a slack channel, https://silverstripe-users.slack.com/messages

**Comment by sheadawson** [comment]
Hi @MondID, I'd love to help but don't have capacity for any extra work at the moment sorry. Please try the IRC channel. Best :)
