### ISSUE TITLE
TinyMCE placeholders not being reverted to shortcode format before save to DB

### ISSUE THREAD

**Issue by jonom** [sheadawson/silverstripe-shortcodable#49]
As @tomstgeorge noted in #45, [this commit](https://github.com/sheadawson/silverstripe-shortcodable/commit/165ce3b013aef1db6f0dea0ba08b97e7e81428f0) has caused a breaking regression

> just made this edit to shortcodable.js and it does fix the 'edit HTML source not saving' issue but breaks the saving of the inserted shortcode dataobject.
Now when I publish the page the embeded shortocde dataobject shows on the frontend as an image i.e. they are no longer being converted into shortcodes on save.
When I look in the database they are stored as the image and not being saved as e.g [myObject id="2"]

**Comment by sheadawson** [comment]
Yes this is not cool, I don't have time to look at it at the moment but can merge right away if anyone submits a fix
