### ISSUE TITLE
Branches/master & tagging

### ISSUE THREAD

**Issue by micschk** [sheadawson/silverstripe-shortcodable#72]
@sheadawson, what's the purpose of the 4.0 branch? Isn't master supposed to be aiming for 4.0 compat? And then 4.x.x tags based of master? (just so I can help & work in the correct structure)

**Comment by sheadawson** [comment]
@micschk feel free to use master for 4.0 dev and 3.x branch for 3.

**Comment by micschk** [comment]
Thx!
