### ISSUE TITLE
Rich placeholders for shortcodes

### ISSUE THREAD

**Issue by jonom** [sheadawson/silverstripe-shortcodable#9]
As touched on here https://github.com/sheadawson/silverstripe-shortcodable/issues/6#issuecomment-57972237

With this module installed there shouldn't be any need to directly edit shortcode properties in the editor so it would be great to replace the shortcode text with a visual placeholder.

Clicking anywhere on the placeholder could open the shortcode editing form.

Placeholder could perhaps be rendered via ajax by sending shortcode arguments to a `Placeholder()` method defined on each class that implements ShortCodable. That way a rich preview could be shown for each shortcode instance.

**Comment by satrun77** [comment]
I'm currently working on this feature. I'm planning to create a pull request if I'm happy with the code.

**Comment by sheadawson** [comment]
Behold! https://github.com/sheadawson/silverstripe-shortcodable/tree/2.0.2 

Fixed in #32

**Comment by jonom** [comment]
Awesome! Thanks for your efforts guys!
